### ISSUE TITLE
civitai probably update caused shortcut to fail obtaining files

### ISSUE THREAD

**Issue by yimogit** [sunnyark/civitai-shortcut#13]
Error message: `The loading of the shortcut file has failed or it is empty`
My  sdui version is 22bcc7be，
I have tried everything from browser to browser, desktop to browser
Hope to receive help, thank you

**Comment by sunnyark** [comment]
Has the CivitaiShortCut.json file been created in the folder where the extension is installed? Please copy the following URL and paste it into the upload text field. Could you please explain how it works? 
https://civitai.com/models/37458/civitai-shortcut

**Comment by yimogit** [comment]
yes，created，but use your link also error
![image](https://github.com/sunnyark/civitai-shortcut/assets/15975059/94aa556b-9c0d-43eb-9f6b-405d97485d8b)

![image](https://github.com/sunnyark/civitai-shortcut/assets/15975059/7d087363-74c0-4f68-92dd-50827ab7654e)

**Comment by sunnyark** [comment]
@yimogit There is not enough information to determine the cause. If there are no registrations at all, then it is normal for that message to appear, but it should not appear if there is even one registration. Rather than a problem with the code, could it be an issue with the environment? Is it possible to see a video of it in action?
