### ISSUE TITLE
Unable to choose which file to download.

### ISSUE THREAD

**Issue by Dreadfxl** [sunnyark/civitai-shortcut#18]
Hello,

With the newest version of civitai shortcut I cannot choose which specific file to download.
The only option is to download every file.

Can you make it so I can choose specific files?

Thank you

**Comment by sunnyark** [comment]
Is this not working? Could you please let me know what operating environment you are using?
![download](https://github.com/sunnyark/civitai-shortcut/assets/40237431/6e5f4292-28b1-4275-9b76-788f07dc411b)

**Comment by Dreadfxl** [comment]
That's it, that doesn't work for me. When I choose one of the options it gets stuck on "queue" and "processing", "queue" and "processing", on a loop.

I'm using Windows 11 Pro, with the "COMMANDLINE_ARGS=--listen" on the .bat launch file so I can run Stable Diffusion on other devices.

**Comment by sunnyark** [comment]
I happened to think of VMware, so I tried a remote connection. The PC with SDUI installed was running Windows 11, and VMware was running Ubuntu with Firefox browser. I was able to operate it without any issues.

**Comment by Dreadfxl** [comment]
![chrome_8sKDtl7kqz](https://github.com/sunnyark/civitai-shortcut/assets/32430923/2095100f-2ba1-406b-a833-5928bb7d7692)


This what happens, I've tried with other civitai shortcuts.

**Comment by sunnyark** [comment]
It seems to be stuck in a recursive loop, but it shouldn't be possible since it uses the select event trigger, not the change trigger. It's behaving as if it were triggered by the change event, so it appears to be influenced unexpectedly from somewhere.
Is it possible to turn off other extensions and try running it?

**Comment by Dreadfxl** [comment]
![image](https://github.com/sunnyark/civitai-shortcut/assets/32430923/d6b490e3-dbcd-41cc-a0c7-5de7dffc7f9d)

Now that I removed every extension and left only civitai it gives me this error.

**Comment by sunnyark** [comment]
It would have been enough to uncheck it in the extensions tab, but it seems like you deleted it completely. 😢
If you reinstall it, please make sure to keep the files CivitaiShortCut.json and CivitaiShortCutClassification.json, as they contain the saved shortcuts and classification information. Replace these two files after reinstalling.
Anyway , it's frustrating that it's still the same even after trying that.

**Comment by sunnyark** [comment]
It seems like I also encounter the last error screen while updating SDUI. I will need to investigate and check it out.

**Comment by Dreadfxl** [comment]
Little update: I've reinstalled the extension and still gives me the same error.

**Comment by sunnyark** [comment]
That error was not related to updating SDUI, but rather a problem that arose from changes in the model information specification in Civitai. Data needs to be updated. I have uploaded the fix urgently. To update the data, you can execute "Manage -> Scan and Update Model -> Update the model information for the shortcut," and it will download and retrieve the latest information. 😢

**Comment by Dreadfxl** [comment]
Ok, so the extension is working again but the original problem still remains.
I have disabled every extension and only left civitai on.

![chrome_lR0nHAZy6R](https://github.com/sunnyark/civitai-shortcut/assets/32430923/ff5ebf8e-ed77-4a5d-8f59-2d4247b73c1e)

**Comment by sunnyark** [comment]
Shall we proceed like this? Since I can't reproduce that situation, it might take some time to identify the cause. Since what you need is to select a file and download it, I'll make that possible for you.
You need some source code modifications. There are two files

The files are located in scripts -> civitai_manager_libs:
civitai_action.py
ishortcut_action.py

Please change line 45 of civitai_action.py as follows:

Change:
filename_list = gr.CheckboxGroup(show_label=False, label="Model Version File", choices=[], value=[], interactive=True, visible=False)

To:
filename_list = gr.CheckboxGroup(show_label=False, label="Model Version File", choices=[], value=[], interactive=True, visible=True)

Please change line 42 of ishortcut_action.py as follows:

Change:
filename_list = gr.CheckboxGroup(show_label=False, label="Model Version File", choices=[], value=[], interactive=True, visible=False)

To:
filename_list = gr.CheckboxGroup(show_label=False, label="Model Version File", choices=[], value=[], interactive=True, visible=True)


Afterwards, when you run it, you will see an option to select the file below the list of download options. From now on, you can use this option to make your selection.
It seems that using a trick to add checkbox boxes to Gradio's dataframe has caused some issues.

If you encounter the same issue in the next version, please try making a similar modification or reach out to me for assistance.

**Comment by Dreadfxl** [comment]
I've changed those two lines and the problem still happens.

I don't know if this helps, but I get this information on the console whenever I upload a civitai url

![image](https://github.com/sunnyark/civitai-shortcut/assets/32430923/90b64e5b-d8f1-4479-afec-eb0f097e1f24)

**Comment by Dreadfxl** [comment]
![image](https://github.com/sunnyark/civitai-shortcut/assets/32430923/a8411f34-4392-4d66-a6cc-09f3f77efbb9)

Thank you!! this way is working!!

**Comment by sunnyark** [comment]
I'm glad to hear that it's working.
Can I check the version information that appears at the bottom? I'm curious and would like to verify it.
like this.
![스크린샷 2023-05-20 223247](https://github.com/sunnyark/civitai-shortcut/assets/40237431/117416a0-f66a-43bf-8be3-7adc7f447576)

**Comment by Dreadfxl** [comment]
![image](https://github.com/sunnyark/civitai-shortcut/assets/32430923/dcdd580b-395f-44e9-9d50-6663a6682839)

**Comment by sunnyark** [comment]
When you have the chance, I recommend updating sdui.

**Comment by Dreadfxl** [comment]
> When you have the chance, I recommend updating sdui.

How do I do that? I use git pull on my launch bat, is that it?

**Comment by Dreadfxl** [comment]
![image](https://github.com/sunnyark/civitai-shortcut/assets/32430923/2056a4f0-91a7-4bb7-bde8-816bd96c9677)

**Comment by sunnyark** [comment]
I should have thought of this first... I'm glad it's going well.
