### ISSUE TITLE
[Debug] User Gallery issue 

### ISSUE THREAD

**Issue by alexwchvui** [sunnyark/civitai-shortcut#40]
I upgraded the latest version.
(Standard) 12 images per page.
I continuing clicked the [Next Page] button ... the Page changed from Page 1 -> 2 -> 3 -> 1 -> 2 -> 3 -> (not able proceed Page 4, keep return back to Page 1)

Civitai Shortcut: Request failed with status code: 503
Civitai Shortcut: Request failed with status code: 503
Civitai Shortcut: Request failed with status code: 500
Civitai Shortcut: Request failed with status code: 500
Civitai Shortcut: Request failed with status code: 503
Civitai Shortcut: 'NoneType' object is not subscriptable
Civitai Shortcut: Request failed with status code: 429
Civitai Shortcut: Request failed with status code: 500
Civitai Shortcut: Request failed with status code: 500
Civitai Shortcut: Request failed with status code: 500

And Page loading speed very slow. (My Internet Speed Test : Download : 133.69Mbps , Upload : 58.44Mbps) 

Please help. (*1 month ago used it very smooth.)

**Comment by sunnyark** [comment]
The civitai API has recently been updated, and due to our inability to make the necessary changes in time, there were issues with page navigation. However, we have now made the required modifications, and these changes will be reflected once you update the system. Additionally, if you encounter a status code error, it indicates a problem with the connection to the civitai website. While there could be various causes for this issue, one possible solution within the current program is to disable preloading of Gallera's images, which can help reduce the load on the connection. When rapidly navigating through pages, the overlapping image download threads can strain the connection. To implement this solution, you need to directly modify the setting.py file. 
To make the necessary change, please modify line 120 of the setting.py file. Change 'usergallery_preloading = True' to 'usergallery_preloading = False'. Thank you for letting us know, and we apologize for any inconvenience caused.

**Comment by sunnyark** [comment]
@alexwchvui Did you make the adjustment to set the number of images per page to 12 in the 'manage->setting: user gallery' or did you directly modify it in the source code?

**Comment by alexwchvui** [comment]
Thanks for the instructions.
I changed 'usergallery_preloading = True' to 'usergallery_preloading = False'  -> Result : the Page loading speed become smoother.

I tried below ....

Model : ChikMix
(Standard) 12 images per page.
Total Page : 202 page
Able load image from Page 1 - 70 , Page 71 - 202 failed load image.
Civitai Shortcut: Request failed with status code: 503
Civitai Shortcut: Request failed with status code: 429
Civitai Shortcut: Request failed with status code: 429
Civitai Shortcut: Request failed with status code: 429
Civitai Shortcut: Request failed with status code: 429
Civitai Shortcut: Request failed with status code: 429
Civitai Shortcut: Request failed with status code: 429
Civitai Shortcut: Request failed with status code: 429
Civitai Shortcut: Request failed with status code: 429
Civitai Shortcut: Request failed with status code: 429
Civitai Shortcut: Request failed with status code: 429
Civitai Shortcut: Request failed with status code: 429

**Comment by sunnyark** [comment]
I haven't had a chance to test it with such a large number of pages, but it seems to be showing the same error. I'll need to do more testing.

**Comment by sunnyark** [comment]
@alexwchvui After checking the return data, I found that it is returning this value: {"error":"You've requested too many pages, please use cursors instead."}.
It seems that Civitai has imposed limitations on the number of pages they provide with the API change. It looks like I'll need to make overall changes to the gallery. It might take some time.

**Comment by alexwchvui** [comment]
Civitai Shortcut is powerful tool and save lot of time to download the gallery i need for learning purpose.
ok , i will wait your next upgrade version. Thanks.

**Comment by alexwchvui** [comment]
Civitai Shortcut is powerful tool and save lot of time to download the gallery i need for learning purpose.
ok , i will wait your next upgrade version. Thanks.

**Comment by alexwchvui** [comment]
It's work . thanks for the upgrade. :D
